/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module uart(clk, rst, tx_start, tx_data, tx, tx_busy, rx, rx_data, rx_valid);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  input clk;
  wire clk;
  input rst;
  wire rst;
  input rx;
  wire rx;
  wire [2:0] rx_bit_count;
  wire [15:0] rx_clk_count;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  wire [7:0] rx_shift_reg;
  wire [3:0] rx_state;
  output rx_valid;
  wire rx_valid;
  output tx;
  wire tx;
  wire [2:0] tx_bit_count;
  output tx_busy;
  wire tx_busy;
  wire [15:0] tx_clk_count;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  wire [7:0] tx_shift_reg;
  input tx_start;
  wire tx_start;
  wire [3:0] tx_state;
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(tx_clk_count[12]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(tx_clk_count[11]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(rx_clk_count[14]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _281_ (
    .A(rx_clk_count[13]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(rx_clk_count[9]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _283_ (
    .A(rx_clk_count[8]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _284_ (
    .A(rx_clk_count[7]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(tx_state[0]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(rx),
    .Y(_081_)
  );
  sky130_fd_sc_hd__clkinv_1 _287_ (
    .A(rx_state[2]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__and4_1 _288_ (
    .A(rx_clk_count[3]),
    .B(rx_clk_count[2]),
    .C(rx_clk_count[1]),
    .D(rx_clk_count[0]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _289_ (
    .A(rx_clk_count[3]),
    .B(rx_clk_count[2]),
    .C(rx_clk_count[1]),
    .D(rx_clk_count[0]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__or4_1 _290_ (
    .A(rx_clk_count[7]),
    .B(rx_clk_count[6]),
    .C(rx_clk_count[5]),
    .D(rx_clk_count[4]),
    .X(_085_)
  );
  sky130_fd_sc_hd__or4_1 _291_ (
    .A(rx_clk_count[11]),
    .B(rx_clk_count[10]),
    .C(rx_clk_count[9]),
    .D(rx_clk_count[8]),
    .X(_086_)
  );
  sky130_fd_sc_hd__or4_1 _292_ (
    .A(rx_clk_count[15]),
    .B(rx_clk_count[14]),
    .C(rx_clk_count[13]),
    .D(rx_clk_count[12]),
    .X(_087_)
  );
  sky130_fd_sc_hd__nor4_1 _293_ (
    .A(_084_),
    .B(_085_),
    .C(_086_),
    .D(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2b_1 _294_ (
    .A_N(_088_),
    .B(rx_state[3]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(rx_bit_count[1]),
    .B(rx_bit_count[0]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(rx_bit_count[2]),
    .B(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and2_0 _297_ (
    .A(rx_state[1]),
    .B(_088_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(rx_state[1]),
    .B(_088_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand4_1 _299_ (
    .A(rx_bit_count[2]),
    .B(rx_bit_count[1]),
    .C(rx_bit_count[0]),
    .D(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _300_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _301_ (
    .A1(_089_),
    .A2(_094_),
    .B1(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(tx_start),
    .B(tx_state[0]),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(tx_start),
    .B(tx_state[0]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and4_1 _304_ (
    .A(tx_clk_count[3]),
    .B(tx_clk_count[2]),
    .C(tx_clk_count[1]),
    .D(tx_clk_count[0]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor4_1 _305_ (
    .A(tx_clk_count[7]),
    .B(tx_clk_count[6]),
    .C(tx_clk_count[5]),
    .D(tx_clk_count[4]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4_1 _306_ (
    .A(tx_clk_count[11]),
    .B(tx_clk_count[10]),
    .C(tx_clk_count[9]),
    .D(tx_clk_count[8]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _307_ (
    .A(tx_clk_count[15]),
    .B(tx_clk_count[14]),
    .C(tx_clk_count[13]),
    .D(tx_clk_count[12]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__and4_1 _308_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .D(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(rst),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(tx_state[2]),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _311_ (
    .A1(rst),
    .A2(_097_),
    .B1(_104_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(rx_state[3]),
    .B(_088_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(rx_state[3]),
    .A2(_088_),
    .B1(rst),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(rx_state[0]),
    .B(rx),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand4b_1 _315_ (
    .A_N(rx_clk_count[3]),
    .B(rx_clk_count[2]),
    .C(rx_clk_count[1]),
    .D(rx_clk_count[0]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor4_1 _316_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .D(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _317_ (
    .A(rx),
    .B(rx_state[2]),
    .C(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand3_1 _318_ (
    .A(_106_),
    .B(_107_),
    .C(_110_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__o21ai_0 _319_ (
    .A1(_090_),
    .A2(_091_),
    .B1(rx_state[1]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _320_ (
    .A(_081_),
    .B(rx_state[2]),
    .C(_109_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_111_),
    .A2(_112_),
    .B1(rst),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(tx_state[3]),
    .B(_103_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand4_1 _323_ (
    .A(tx_bit_count[2]),
    .B(tx_bit_count[1]),
    .C(tx_bit_count[0]),
    .D(_102_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__and2_0 _324_ (
    .A(tx_state[1]),
    .B(_102_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand4_1 _325_ (
    .A(tx_bit_count[2]),
    .B(tx_bit_count[1]),
    .C(tx_bit_count[0]),
    .D(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _326_ (
    .A1(rst),
    .A2(_116_),
    .B1(_113_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _327_ (
    .A(rst),
    .B(tx_state[3]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_103_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o22ai_1 _329_ (
    .A1(tx_start),
    .A2(_080_),
    .B1(_103_),
    .B2(_117_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a22oi_1 _330_ (
    .A1(tx_state[2]),
    .A2(_102_),
    .B1(_114_),
    .B2(tx_state[1]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(rst),
    .B(_119_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _332_ (
    .A(_082_),
    .SLEEP(_109_),
    .X(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(rx_state[0]),
    .B(_081_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a21oi_1 _334_ (
    .A1(_120_),
    .A2(_121_),
    .B1(rst),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _335_ (
    .A(rst),
    .B(_105_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a22o_1 _336_ (
    .A1(rx_data[0]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[0]),
    .X(_008_)
  );
  sky130_fd_sc_hd__a22o_1 _337_ (
    .A1(rx_data[1]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[1]),
    .X(_009_)
  );
  sky130_fd_sc_hd__a22o_1 _338_ (
    .A1(rx_data[2]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[2]),
    .X(_010_)
  );
  sky130_fd_sc_hd__a22o_1 _339_ (
    .A1(rx_data[3]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[3]),
    .X(_011_)
  );
  sky130_fd_sc_hd__a22o_1 _340_ (
    .A1(rx_data[4]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[4]),
    .X(_012_)
  );
  sky130_fd_sc_hd__a22o_1 _341_ (
    .A1(rx_data[5]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[5]),
    .X(_013_)
  );
  sky130_fd_sc_hd__a22o_1 _342_ (
    .A1(rx_data[6]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[6]),
    .X(_014_)
  );
  sky130_fd_sc_hd__a22o_1 _343_ (
    .A1(rx_data[7]),
    .A2(_106_),
    .B1(_043_),
    .B2(rx_shift_reg[7]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(rx_state[1]),
    .B(rx_state[3]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor3_1 _345_ (
    .A(rx_state[1]),
    .B(rx_state[3]),
    .C(rx_state[2]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(_082_),
    .B(_122_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21a_1 _347_ (
    .A1(rx_state[0]),
    .A2(_124_),
    .B1(_110_),
    .X(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _348_ (
    .A1(rx_state[0]),
    .A2(_124_),
    .B1(_110_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(rx_clk_count[0]),
    .B(_124_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a211oi_1 _350_ (
    .A1(rx_clk_count[0]),
    .A2(_125_),
    .B1(_127_),
    .C1(rst),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _351_ (
    .A1(rx_clk_count[1]),
    .A2(rx_clk_count[0]),
    .B1(_123_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _352_ (
    .A(_126_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a21oi_1 _353_ (
    .A1(rx_clk_count[0]),
    .A2(_124_),
    .B1(rx_clk_count[1]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor3_1 _354_ (
    .A(rst),
    .B(_129_),
    .C(_130_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(rx_clk_count[1]),
    .A2(rx_clk_count[0]),
    .A3(_124_),
    .B1(rx_clk_count[2]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a211oi_1 _356_ (
    .A1(rx_clk_count[2]),
    .A2(_129_),
    .B1(_131_),
    .C1(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a41oi_1 _357_ (
    .A1(rx_clk_count[2]),
    .A2(rx_clk_count[1]),
    .A3(rx_clk_count[0]),
    .A4(_125_),
    .B1(rx_clk_count[3]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _358_ (
    .A1(_120_),
    .A2(_122_),
    .B1(_083_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(_126_),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor3_1 _360_ (
    .A(rst),
    .B(_132_),
    .C(_134_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and2_0 _361_ (
    .A(rx_clk_count[4]),
    .B(_083_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a211oi_1 _362_ (
    .A1(_082_),
    .A2(_088_),
    .B1(_123_),
    .C1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _363_ (
    .A1(rx_clk_count[4]),
    .A2(_126_),
    .B1(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _364_ (
    .A(rx_clk_count[4]),
    .B(_083_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor3_1 _365_ (
    .A(rst),
    .B(_137_),
    .C(_138_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _366_ (
    .A1(rx_clk_count[5]),
    .A2(_135_),
    .B1(_123_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _367_ (
    .A1(rx_clk_count[5]),
    .A2(_126_),
    .B1(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(rx_clk_count[5]),
    .B(_135_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3_1 _369_ (
    .A(rst),
    .B(_140_),
    .C(_141_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand4_1 _370_ (
    .A(rx_clk_count[6]),
    .B(rx_clk_count[5]),
    .C(rx_clk_count[4]),
    .D(_083_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a22oi_1 _371_ (
    .A1(rx_clk_count[6]),
    .A2(_126_),
    .B1(_142_),
    .B2(_124_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _372_ (
    .A1(rx_clk_count[5]),
    .A2(_135_),
    .B1(rx_clk_count[6]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor3_1 _373_ (
    .A(rst),
    .B(_143_),
    .C(_144_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(_079_),
    .B(_142_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _375_ (
    .A(_123_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(rx_clk_count[7]),
    .A2(_126_),
    .B1(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a211oi_1 _377_ (
    .A1(_079_),
    .A2(_142_),
    .B1(_147_),
    .C1(rst),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(rx_clk_count[8]),
    .B(_145_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a22oi_1 _379_ (
    .A1(rx_clk_count[8]),
    .A2(_126_),
    .B1(_148_),
    .B2(_124_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(rx_clk_count[8]),
    .B(_145_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _381_ (
    .A(rst),
    .B(_149_),
    .C(_150_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor4_1 _382_ (
    .A(_077_),
    .B(_078_),
    .C(_079_),
    .D(_142_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _383_ (
    .A1_N(_123_),
    .A2_N(_151_),
    .B1(_126_),
    .B2(rx_clk_count[9]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a211oi_1 _384_ (
    .A1(_077_),
    .A2(_148_),
    .B1(_152_),
    .C1(rst),
    .Y(_025_)
  );
  sky130_fd_sc_hd__and2_0 _385_ (
    .A(rx_clk_count[10]),
    .B(_151_),
    .X(_153_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _386_ (
    .A1_N(_123_),
    .A2_N(_153_),
    .B1(_126_),
    .B2(rx_clk_count[10]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _387_ (
    .A(rx_clk_count[10]),
    .B(_151_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor3_1 _388_ (
    .A(rst),
    .B(_154_),
    .C(_155_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a31oi_1 _389_ (
    .A1(rx_clk_count[11]),
    .A2(rx_clk_count[10]),
    .A3(_151_),
    .B1(_123_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _390_ (
    .A1(rx_clk_count[11]),
    .A2(_126_),
    .B1(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nor2_1 _391_ (
    .A(rx_clk_count[11]),
    .B(_153_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor3_1 _392_ (
    .A(rst),
    .B(_157_),
    .C(_158_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and4_1 _393_ (
    .A(rx_clk_count[12]),
    .B(rx_clk_count[11]),
    .C(rx_clk_count[10]),
    .D(_151_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand4_1 _394_ (
    .A(rx_clk_count[12]),
    .B(rx_clk_count[11]),
    .C(rx_clk_count[10]),
    .D(_151_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a22oi_1 _395_ (
    .A1(rx_clk_count[12]),
    .A2(_126_),
    .B1(_160_),
    .B2(_124_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _396_ (
    .A1(rx_clk_count[11]),
    .A2(_153_),
    .B1(rx_clk_count[12]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor3_1 _397_ (
    .A(rst),
    .B(_161_),
    .C(_162_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(_076_),
    .A2(_160_),
    .B1(_124_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _399_ (
    .A1(_124_),
    .A2(_159_),
    .B1(rx_clk_count[13]),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a211oi_1 _400_ (
    .A1(_125_),
    .A2(_163_),
    .B1(_164_),
    .C1(rst),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o31ai_1 _401_ (
    .A1(_075_),
    .A2(_076_),
    .A3(_160_),
    .B1(_124_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand3_1 _402_ (
    .A(rx_clk_count[13]),
    .B(_124_),
    .C(_159_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a221oi_1 _403_ (
    .A1(_125_),
    .A2(_165_),
    .B1(_166_),
    .B2(_075_),
    .C1(rst),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a41oi_1 _404_ (
    .A1(rx_clk_count[14]),
    .A2(rx_clk_count[13]),
    .A3(_124_),
    .A4(_159_),
    .B1(rx_clk_count[15]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a311oi_1 _405_ (
    .A1(rx_clk_count[15]),
    .A2(_125_),
    .A3(_165_),
    .B1(_167_),
    .C1(rst),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2b_1 _406_ (
    .A_N(rx_state[1]),
    .B(rx_state[0]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(_093_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(rx_bit_count[0]),
    .B(_092_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a211oi_1 _409_ (
    .A1(rx_bit_count[0]),
    .A2(_169_),
    .B1(_170_),
    .C1(rst),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(rx_bit_count[1]),
    .B(rx_bit_count[0]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor3b_1 _411_ (
    .A(_093_),
    .B(_171_),
    .C_N(_090_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a31oi_1 _412_ (
    .A1(rx_bit_count[1]),
    .A2(_093_),
    .A3(_168_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(rst),
    .B(_173_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _414_ (
    .A1(rx_bit_count[1]),
    .A2(rx_bit_count[0]),
    .B1(rx_bit_count[2]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _415_ (
    .A1(rx_bit_count[2]),
    .A2(_168_),
    .B1(_092_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor4_1 _416_ (
    .A(rst),
    .B(_095_),
    .C(_174_),
    .D(_175_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _417_ (
    .A(rx_bit_count[2]),
    .B(rx_bit_count[1]),
    .C(rx_bit_count[0]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a21oi_1 _418_ (
    .A1(_092_),
    .A2(_176_),
    .B1(rx_shift_reg[0]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a311oi_1 _419_ (
    .A1(_081_),
    .A2(_092_),
    .A3(_176_),
    .B1(_177_),
    .C1(rst),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _420_ (
    .A(rx_bit_count[2]),
    .B(_171_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__and3_1 _421_ (
    .A(rx_state[1]),
    .B(_088_),
    .C(_178_),
    .X(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(_092_),
    .B(_178_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _423_ (
    .A(rx_bit_count[0]),
    .SLEEP(rx_bit_count[1]),
    .X(_181_)
  );
  sky130_fd_sc_hd__nand2b_1 _424_ (
    .A_N(rx_bit_count[1]),
    .B(rx_bit_count[0]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o21ai_0 _425_ (
    .A1(_180_),
    .A2(_182_),
    .B1(rx_shift_reg[1]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand3_1 _426_ (
    .A(rx),
    .B(_179_),
    .C(_181_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a21oi_1 _427_ (
    .A1(_183_),
    .A2(_184_),
    .B1(rst),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _428_ (
    .A(rx_bit_count[1]),
    .SLEEP(rx_bit_count[0]),
    .X(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _429_ (
    .A1(_179_),
    .A2(_185_),
    .B1(rx_shift_reg[2]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a311oi_1 _430_ (
    .A1(_081_),
    .A2(_179_),
    .A3(_185_),
    .B1(_186_),
    .C1(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o21ai_0 _431_ (
    .A1(_090_),
    .A2(_180_),
    .B1(rx_shift_reg[3]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _432_ (
    .A(_081_),
    .B(_090_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(_179_),
    .B(_188_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _434_ (
    .A1(_187_),
    .A2(_189_),
    .B1(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(rx_bit_count[2]),
    .B(_092_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a31oi_1 _436_ (
    .A1(rx_bit_count[2]),
    .A2(_092_),
    .A3(_171_),
    .B1(rx_shift_reg[4]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor4_1 _437_ (
    .A(rx_bit_count[1]),
    .B(rx_bit_count[0]),
    .C(rx),
    .D(_190_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor3_1 _438_ (
    .A(rst),
    .B(_191_),
    .C(_192_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(_093_),
    .B(_178_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21ai_0 _440_ (
    .A1(_182_),
    .A2(_190_),
    .B1(rx_shift_reg[5]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand3_1 _441_ (
    .A(rx),
    .B(_181_),
    .C(_193_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a21oi_1 _442_ (
    .A1(_194_),
    .A2(_195_),
    .B1(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand3_1 _443_ (
    .A(rx_bit_count[2]),
    .B(_092_),
    .C(_185_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a32oi_1 _444_ (
    .A1(rx),
    .A2(_185_),
    .A3(_193_),
    .B1(_196_),
    .B2(rx_shift_reg[6]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _445_ (
    .A(rst),
    .B(_197_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a22oi_1 _446_ (
    .A1(rx_shift_reg[7]),
    .A2(_094_),
    .B1(_188_),
    .B2(_193_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(rst),
    .B(_198_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _448_ (
    .A(_080_),
    .B(tx_state[3]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__mux2i_1 _449_ (
    .A0(tx_busy),
    .A1(tx_start),
    .S(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _450_ (
    .A(_118_),
    .B(_200_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux4_2 _451_ (
    .A0(tx_shift_reg[1]),
    .A1(tx_shift_reg[3]),
    .A2(tx_shift_reg[5]),
    .A3(tx_shift_reg[7]),
    .S0(tx_bit_count[1]),
    .S1(tx_bit_count[2]),
    .X(_201_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _452_ (
    .A(tx_bit_count[0]),
    .SLEEP(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd__mux4_2 _453_ (
    .A0(tx_shift_reg[0]),
    .A1(tx_shift_reg[2]),
    .A2(tx_shift_reg[4]),
    .A3(tx_shift_reg[6]),
    .S0(tx_bit_count[1]),
    .S1(tx_bit_count[2]),
    .X(_203_)
  );
  sky130_fd_sc_hd__o21ai_0 _454_ (
    .A1(tx_bit_count[0]),
    .A2(_203_),
    .B1(tx_state[1]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(tx_state[2]),
    .B(tx_state[1]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _456_ (
    .A(rst),
    .B(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _457_ (
    .A1(_202_),
    .A2(_204_),
    .B1(_206_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _458_ (
    .A(tx_state[2]),
    .B(tx_state[3]),
    .C(tx_state[1]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__or3_1 _459_ (
    .A(tx_state[2]),
    .B(tx_state[3]),
    .C(tx_state[1]),
    .X(_208_)
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(tx_state[0]),
    .B(_207_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2b_1 _461_ (
    .A_N(rst),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__xnor2_1 _462_ (
    .A(tx_clk_count[0]),
    .B(_208_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(tx_state[0]),
    .B(_208_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(_210_),
    .B(_211_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a21oi_1 _465_ (
    .A1(tx_clk_count[1]),
    .A2(tx_clk_count[0]),
    .B1(_207_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a21oi_1 _466_ (
    .A1(tx_clk_count[1]),
    .A2(_212_),
    .B1(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(tx_clk_count[1]),
    .B(tx_clk_count[0]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nor3_1 _468_ (
    .A(rst),
    .B(_214_),
    .C(_215_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a31oi_1 _469_ (
    .A1(tx_clk_count[2]),
    .A2(tx_clk_count[1]),
    .A3(tx_clk_count[0]),
    .B1(_207_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _470_ (
    .A1(tx_clk_count[2]),
    .A2(_212_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__a21oi_1 _471_ (
    .A1(tx_clk_count[1]),
    .A2(tx_clk_count[0]),
    .B1(tx_clk_count[2]),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nor3_1 _472_ (
    .A(rst),
    .B(_217_),
    .C(_218_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _473_ (
    .A(_098_),
    .B(_207_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a21oi_1 _474_ (
    .A1(tx_clk_count[3]),
    .A2(_212_),
    .B1(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a31oi_1 _475_ (
    .A1(tx_clk_count[2]),
    .A2(tx_clk_count[1]),
    .A3(tx_clk_count[0]),
    .B1(tx_clk_count[3]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor3_1 _476_ (
    .A(rst),
    .B(_220_),
    .C(_221_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(tx_clk_count[4]),
    .B(_212_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor2_1 _478_ (
    .A(rst),
    .B(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__and2_0 _479_ (
    .A(tx_clk_count[4]),
    .B(_098_),
    .X(_224_)
  );
  sky130_fd_sc_hd__nor4_1 _480_ (
    .A(rst),
    .B(_102_),
    .C(_207_),
    .D(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o22a_1 _481_ (
    .A1(tx_clk_count[4]),
    .A2(_098_),
    .B1(_223_),
    .B2(_225_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _482_ (
    .A1(tx_clk_count[5]),
    .A2(_224_),
    .B1(_207_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a21oi_1 _483_ (
    .A1(tx_clk_count[5]),
    .A2(_212_),
    .B1(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nor2_1 _484_ (
    .A(tx_clk_count[5]),
    .B(_224_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _485_ (
    .A(rst),
    .B(_227_),
    .C(_228_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and4_1 _486_ (
    .A(tx_clk_count[6]),
    .B(tx_clk_count[5]),
    .C(tx_clk_count[4]),
    .D(_098_),
    .X(_229_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _487_ (
    .A1_N(_207_),
    .A2_N(_229_),
    .B1(_212_),
    .B2(tx_clk_count[6]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__a21oi_1 _488_ (
    .A1(tx_clk_count[5]),
    .A2(_224_),
    .B1(tx_clk_count[6]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nor3_1 _489_ (
    .A(rst),
    .B(_230_),
    .C(_231_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and2_0 _490_ (
    .A(tx_clk_count[7]),
    .B(_229_),
    .X(_232_)
  );
  sky130_fd_sc_hd__nor2_1 _491_ (
    .A(_207_),
    .B(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21oi_1 _492_ (
    .A1(tx_clk_count[7]),
    .A2(_212_),
    .B1(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nor2_1 _493_ (
    .A(tx_clk_count[7]),
    .B(_229_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor3_1 _494_ (
    .A(rst),
    .B(_234_),
    .C(_235_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21oi_1 _495_ (
    .A1(tx_clk_count[8]),
    .A2(_232_),
    .B1(_207_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a21oi_1 _496_ (
    .A1(tx_clk_count[8]),
    .A2(_212_),
    .B1(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _497_ (
    .A(tx_clk_count[8]),
    .B(_232_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor3_1 _498_ (
    .A(rst),
    .B(_237_),
    .C(_238_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and3_1 _499_ (
    .A(tx_clk_count[9]),
    .B(tx_clk_count[8]),
    .C(_232_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nand4_1 _500_ (
    .A(tx_clk_count[9]),
    .B(tx_clk_count[8]),
    .C(tx_clk_count[7]),
    .D(_229_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a22oi_1 _501_ (
    .A1(tx_clk_count[9]),
    .A2(_212_),
    .B1(_240_),
    .B2(_208_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a21oi_1 _502_ (
    .A1(tx_clk_count[8]),
    .A2(_232_),
    .B1(tx_clk_count[9]),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor3_1 _503_ (
    .A(rst),
    .B(_241_),
    .C(_242_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a21oi_1 _504_ (
    .A1(_208_),
    .A2(_239_),
    .B1(tx_clk_count[10]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(tx_clk_count[10]),
    .B(_208_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor2_1 _506_ (
    .A(_240_),
    .B(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nor3_1 _507_ (
    .A(_210_),
    .B(_243_),
    .C(_245_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21ai_0 _508_ (
    .A1(_240_),
    .A2(_244_),
    .B1(_074_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand4_1 _509_ (
    .A(tx_clk_count[11]),
    .B(tx_clk_count[10]),
    .C(_208_),
    .D(_239_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__and3b_1 _510_ (
    .A_N(_210_),
    .B(_246_),
    .C(_247_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _511_ (
    .A(tx_clk_count[12]),
    .B(_209_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor4_1 _512_ (
    .A(_073_),
    .B(_074_),
    .C(_240_),
    .D(_244_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__a211oi_1 _513_ (
    .A1(_247_),
    .A2(_248_),
    .B1(_249_),
    .C1(rst),
    .Y(_058_)
  );
  sky130_fd_sc_hd__and2_0 _514_ (
    .A(tx_clk_count[13]),
    .B(_249_),
    .X(_250_)
  );
  sky130_fd_sc_hd__a21oi_1 _515_ (
    .A1(tx_clk_count[13]),
    .A2(_209_),
    .B1(_249_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor3_1 _516_ (
    .A(rst),
    .B(_250_),
    .C(_251_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand3_1 _517_ (
    .A(tx_clk_count[14]),
    .B(tx_clk_count[13]),
    .C(_249_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__a22oi_1 _518_ (
    .A1(tx_clk_count[14]),
    .A2(_209_),
    .B1(_249_),
    .B2(tx_clk_count[13]),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a211oi_1 _519_ (
    .A1(tx_clk_count[14]),
    .A2(_250_),
    .B1(_253_),
    .C1(rst),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _520_ (
    .A(tx_clk_count[15]),
    .B(rst),
    .Y(_254_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _521_ (
    .A(tx_clk_count[15]),
    .SLEEP(_210_),
    .X(_255_)
  );
  sky130_fd_sc_hd__mux2_1 _522_ (
    .A0(_254_),
    .A1(_255_),
    .S(_252_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _523_ (
    .A(_080_),
    .B(tx_state[1]),
    .Y(_256_)
  );
  sky130_fd_sc_hd__o21a_1 _524_ (
    .A1(_115_),
    .A2(_256_),
    .B1(tx_bit_count[0]),
    .X(_257_)
  );
  sky130_fd_sc_hd__nor2_1 _525_ (
    .A(tx_bit_count[0]),
    .B(_115_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor3_1 _526_ (
    .A(rst),
    .B(_257_),
    .C(_258_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _527_ (
    .A(rst),
    .B(_256_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__xnor2_1 _528_ (
    .A(tx_bit_count[1]),
    .B(_257_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor3_1 _529_ (
    .A(rst),
    .B(_256_),
    .C(_260_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21o_1 _530_ (
    .A1(tx_bit_count[1]),
    .A2(_257_),
    .B1(tx_bit_count[2]),
    .X(_261_)
  );
  sky130_fd_sc_hd__and3_1 _531_ (
    .A(_116_),
    .B(_259_),
    .C(_261_),
    .X(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _532_ (
    .A(tx_shift_reg[0]),
    .B(_097_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nand2_1 _533_ (
    .A(tx_data[0]),
    .B(_096_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__a21oi_1 _534_ (
    .A1(_262_),
    .A2(_263_),
    .B1(rst),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _535_ (
    .A(tx_shift_reg[1]),
    .B(_097_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(tx_data[1]),
    .B(_096_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__a21oi_1 _537_ (
    .A1(_264_),
    .A2(_265_),
    .B1(rst),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _538_ (
    .A(tx_shift_reg[2]),
    .B(_097_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _539_ (
    .A(tx_data[2]),
    .B(_096_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a21oi_1 _540_ (
    .A1(_266_),
    .A2(_267_),
    .B1(rst),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _541_ (
    .A(tx_shift_reg[3]),
    .B(_097_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nand2_1 _542_ (
    .A(tx_data[3]),
    .B(_096_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__a21oi_1 _543_ (
    .A1(_268_),
    .A2(_269_),
    .B1(rst),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _544_ (
    .A(tx_shift_reg[4]),
    .B(_097_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _545_ (
    .A(tx_data[4]),
    .B(_096_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__a21oi_1 _546_ (
    .A1(_270_),
    .A2(_271_),
    .B1(rst),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _547_ (
    .A(tx_shift_reg[5]),
    .B(_097_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nand2_1 _548_ (
    .A(tx_data[5]),
    .B(_096_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__a21oi_1 _549_ (
    .A1(_272_),
    .A2(_273_),
    .B1(rst),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _550_ (
    .A(tx_shift_reg[6]),
    .B(_097_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nand2_1 _551_ (
    .A(tx_data[6]),
    .B(_096_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21oi_1 _552_ (
    .A1(_274_),
    .A2(_275_),
    .B1(rst),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _553_ (
    .A(tx_shift_reg[7]),
    .B(_097_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _554_ (
    .A(tx_data[7]),
    .B(_096_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__a21oi_1 _555_ (
    .A1(_276_),
    .A2(_277_),
    .B1(rst),
    .Y(_072_)
  );
  sky130_fd_sc_hd__dfxtp_1 _556_ (
    .CLK(clk),
    .D(_004_),
    .Q(tx_state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _557_ (
    .CLK(clk),
    .D(_005_),
    .Q(tx_state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _558_ (
    .CLK(clk),
    .D(_006_),
    .Q(tx_state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(clk),
    .D(_007_),
    .Q(tx_state[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(clk),
    .D(_008_),
    .Q(rx_data[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(clk),
    .D(_009_),
    .Q(rx_data[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(clk),
    .D(_010_),
    .Q(rx_data[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(clk),
    .D(_011_),
    .Q(rx_data[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(clk),
    .D(_012_),
    .Q(rx_data[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(clk),
    .D(_013_),
    .Q(rx_data[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(clk),
    .D(_014_),
    .Q(rx_data[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(clk),
    .D(_015_),
    .Q(rx_data[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(clk),
    .D(_016_),
    .Q(rx_clk_count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(clk),
    .D(_017_),
    .Q(rx_clk_count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(clk),
    .D(_018_),
    .Q(rx_clk_count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(clk),
    .D(_019_),
    .Q(rx_clk_count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(clk),
    .D(_020_),
    .Q(rx_clk_count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(clk),
    .D(_021_),
    .Q(rx_clk_count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(clk),
    .D(_022_),
    .Q(rx_clk_count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(clk),
    .D(_023_),
    .Q(rx_clk_count[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(clk),
    .D(_024_),
    .Q(rx_clk_count[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(clk),
    .D(_025_),
    .Q(rx_clk_count[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(clk),
    .D(_026_),
    .Q(rx_clk_count[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(clk),
    .D(_027_),
    .Q(rx_clk_count[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(clk),
    .D(_028_),
    .Q(rx_clk_count[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(clk),
    .D(_029_),
    .Q(rx_clk_count[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _582_ (
    .CLK(clk),
    .D(_030_),
    .Q(rx_clk_count[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _583_ (
    .CLK(clk),
    .D(_031_),
    .Q(rx_clk_count[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _584_ (
    .CLK(clk),
    .D(_032_),
    .Q(rx_bit_count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _585_ (
    .CLK(clk),
    .D(_033_),
    .Q(rx_bit_count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _586_ (
    .CLK(clk),
    .D(_034_),
    .Q(rx_bit_count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _587_ (
    .CLK(clk),
    .D(_035_),
    .Q(rx_shift_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _588_ (
    .CLK(clk),
    .D(_036_),
    .Q(rx_shift_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _589_ (
    .CLK(clk),
    .D(_037_),
    .Q(rx_shift_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _590_ (
    .CLK(clk),
    .D(_038_),
    .Q(rx_shift_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _591_ (
    .CLK(clk),
    .D(_039_),
    .Q(rx_shift_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _592_ (
    .CLK(clk),
    .D(_040_),
    .Q(rx_shift_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _593_ (
    .CLK(clk),
    .D(_041_),
    .Q(rx_shift_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _594_ (
    .CLK(clk),
    .D(_042_),
    .Q(rx_shift_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _595_ (
    .CLK(clk),
    .D(_043_),
    .Q(rx_valid)
  );
  sky130_fd_sc_hd__dfxtp_1 _596_ (
    .CLK(clk),
    .D(_044_),
    .Q(tx_busy)
  );
  sky130_fd_sc_hd__dfxtp_1 _597_ (
    .CLK(clk),
    .D(_045_),
    .Q(tx)
  );
  sky130_fd_sc_hd__dfxtp_1 _598_ (
    .CLK(clk),
    .D(_046_),
    .Q(tx_clk_count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _599_ (
    .CLK(clk),
    .D(_047_),
    .Q(tx_clk_count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _600_ (
    .CLK(clk),
    .D(_048_),
    .Q(tx_clk_count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _601_ (
    .CLK(clk),
    .D(_049_),
    .Q(tx_clk_count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _602_ (
    .CLK(clk),
    .D(_050_),
    .Q(tx_clk_count[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _603_ (
    .CLK(clk),
    .D(_051_),
    .Q(tx_clk_count[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _604_ (
    .CLK(clk),
    .D(_052_),
    .Q(tx_clk_count[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _605_ (
    .CLK(clk),
    .D(_053_),
    .Q(tx_clk_count[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _606_ (
    .CLK(clk),
    .D(_054_),
    .Q(tx_clk_count[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _607_ (
    .CLK(clk),
    .D(_055_),
    .Q(tx_clk_count[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _608_ (
    .CLK(clk),
    .D(_056_),
    .Q(tx_clk_count[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _609_ (
    .CLK(clk),
    .D(_057_),
    .Q(tx_clk_count[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _610_ (
    .CLK(clk),
    .D(_058_),
    .Q(tx_clk_count[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _611_ (
    .CLK(clk),
    .D(_059_),
    .Q(tx_clk_count[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _612_ (
    .CLK(clk),
    .D(_060_),
    .Q(tx_clk_count[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _613_ (
    .CLK(clk),
    .D(_061_),
    .Q(tx_clk_count[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _614_ (
    .CLK(clk),
    .D(_062_),
    .Q(tx_bit_count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _615_ (
    .CLK(clk),
    .D(_063_),
    .Q(tx_bit_count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _616_ (
    .CLK(clk),
    .D(_064_),
    .Q(tx_bit_count[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _617_ (
    .CLK(clk),
    .D(_065_),
    .Q(tx_shift_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _618_ (
    .CLK(clk),
    .D(_066_),
    .Q(tx_shift_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _619_ (
    .CLK(clk),
    .D(_067_),
    .Q(tx_shift_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _620_ (
    .CLK(clk),
    .D(_068_),
    .Q(tx_shift_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _621_ (
    .CLK(clk),
    .D(_069_),
    .Q(tx_shift_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _622_ (
    .CLK(clk),
    .D(_070_),
    .Q(tx_shift_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _623_ (
    .CLK(clk),
    .D(_071_),
    .Q(tx_shift_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _624_ (
    .CLK(clk),
    .D(_072_),
    .Q(tx_shift_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _625_ (
    .CLK(clk),
    .D(_000_),
    .Q(rx_state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _626_ (
    .CLK(clk),
    .D(_001_),
    .Q(rx_state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _627_ (
    .CLK(clk),
    .D(_002_),
    .Q(rx_state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _628_ (
    .CLK(clk),
    .D(_003_),
    .Q(rx_state[3])
  );
endmodule
